apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keyexchange
  namespace: mailserver
spec:
  storageClassName: nfs-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
