apiVersion: v1
kind: ConfigMap
metadata:
  name: basicconfig
  namespace: mailserver
data:
  lsyncd.lua: |
    ----
    -- User configuration file for lsyncd.
    --
    -- Simple example for default rsync.
    --
    settings {
        statusFile = "/tmp/lsyncd.stat",
        statusInterval = 1,
        insist = true,
        nodaemon = true,
    }
